name: Clean Expired Subscriptions

on:
  schedule:
    - cron: '0 */6 * * *'  # هر ۶ ساعت یک‌بار اجرا میشه
  workflow_dispatch:       # اجرای دستی

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run cleanup script
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: node scripts/cleanExpiredSubscriptions.js