name: Clean Expired Subscriptions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # Runs every hour; adjust the cron timing as desired

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run cleaning script
        run: node scripts/cleanExpiredSubscriptions.js
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}